run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive

issues:
  exclude-rules:
    - path: docs/
      linters:
        - revive
        - misspell
    - path: internal/finance/models.go
      text: "stutters; consider calling this"
      linters:
        - revive
    - path: internal/dispatch/model.go
      text: "stutters; consider calling this"
      linters:
        - revive
    - path: internal/dispatch/contracts.go
      text: "stutters; consider calling this"
      linters:
        - revive
    - path: internal/order/contracts.go
      text: "stutters; consider calling this"
      linters:
        - revive
