// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Taxi Platform API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/register": {
            "post": {
                "description": "Registers passenger, driver, or taxi park owner. Personal data consent and terms acceptance are mandatory.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register user",
                "parameters": [
                    {
                        "description": "Registration request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.StartRegistrationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dto.StartRegistrationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns public API health status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "API health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_api.apiHealthResponse"
                        }
                    }
                }
            }
        },
        "/health/live": {
            "get": {
                "description": "Returns process liveness status for orchestrators.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_api.healthResponse"
                        }
                    }
                }
            }
        },
        "/health/ready": {
            "get": {
                "description": "Returns readiness status for traffic routing.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_api.healthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cmd_api.apiHealthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "example": "taxi-platform"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "cmd_api.healthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "dto.StartRegistrationRequest": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "password",
                "personal_data_consent",
                "phone",
                "privacy_policy_version",
                "registration_type",
                "terms_accepted",
                "terms_version"
            ],
            "properties": {
                "city_id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "Ivan"
                },
                "last_name": {
                    "type": "string",
                    "example": "Petrov"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "strong-password"
                },
                "personal_data_consent": {
                    "type": "boolean",
                    "example": true
                },
                "phone": {
                    "type": "string",
                    "example": "+79990000000"
                },
                "privacy_policy_version": {
                    "type": "string",
                    "example": "1.0"
                },
                "registration_type": {
                    "enum": [
                        "passenger",
                        "driver",
                        "taxi_park"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_develoop_taxi-platform_internal_domain.RegistrationType"
                        }
                    ],
                    "example": "passenger"
                },
                "taxi_park": {
                    "$ref": "#/definitions/dto.TaxiParkRegistration"
                },
                "terms_accepted": {
                    "type": "boolean",
                    "example": true
                },
                "terms_version": {
                    "type": "string",
                    "example": "1.0"
                }
            }
        },
        "dto.StartRegistrationResponse": {
            "type": "object",
            "properties": {
                "email_masked": {
                    "type": "string",
                    "example": "u***@example.com"
                },
                "message": {
                    "type": "string",
                    "example": "confirmation codes sent"
                },
                "phone_masked": {
                    "type": "string",
                    "example": "+7*****000"
                },
                "registration_type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_develoop_taxi-platform_internal_domain.RegistrationType"
                        }
                    ],
                    "example": "passenger"
                },
                "role": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_develoop_taxi-platform_internal_domain.UserRole"
                        }
                    ],
                    "example": "passenger"
                },
                "user_id": {
                    "type": "string",
                    "example": "33333333-3333-3333-3333-333333333333"
                }
            }
        },
        "dto.TaxiParkRegistration": {
            "type": "object",
            "properties": {
                "legal_name": {
                    "type": "string",
                    "example": "North Taxi Park LLC"
                },
                "name": {
                    "type": "string",
                    "example": "North Taxi Park"
                },
                "tax_id": {
                    "type": "string",
                    "example": "7700000000"
                }
            }
        },
        "github_com_develoop_taxi-platform_internal_domain.RegistrationType": {
            "type": "string",
            "enum": [
                "passenger",
                "driver",
                "taxi_park"
            ],
            "x-enum-varnames": [
                "RegistrationTypePassenger",
                "RegistrationTypeDriver",
                "RegistrationTypeTaxiPark"
            ]
        },
        "github_com_develoop_taxi-platform_internal_domain.UserRole": {
            "type": "string",
            "enum": [
                "passenger",
                "driver",
                "taxi_park",
                "admin",
                "dispatcher"
            ],
            "x-enum-varnames": [
                "UserRolePassenger",
                "UserRoleDriver",
                "UserRoleTaxiPark",
                "UserRoleAdmin",
                "UserRoleDispatcher"
            ]
        },
        "handler.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "personal data consent required"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter the token with the ` + "`" + `Bearer ` + "`" + ` prefix, for example: Bearer eyJhbGciOi...",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Taxi Platform API",
	Description:      "Production-grade taxi backend API for small cities and rural areas.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
