// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Taxi Platform API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Sends verification code to phone or email. At least one of phone or email must be provided.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Start phone or email login",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AuthLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AuthCodeSentSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Revokes the provided refresh token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout mobile user",
                "parameters": [
                    {
                        "description": "Logout request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LogoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AcceptedSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Returns new access and refresh tokens. Old refresh token must be invalidated by service layer.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Rotate refresh token",
                "parameters": [
                    {
                        "description": "Refresh request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RefreshTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AuthTokenSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Registers passenger, driver, or taxi park owner. Personal data consent and terms acceptance are mandatory.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register user",
                "parameters": [
                    {
                        "description": "Registration request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.StartRegistrationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Success"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/auth/verify-code": {
            "post": {
                "description": "Verifies SMS or email code and returns access/refresh tokens.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Verify login code",
                "parameters": [
                    {
                        "description": "Verification request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AuthVerifyCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AuthTokenSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/driver/location": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Driver mobile clients must send no more than one update per two seconds unless using batch endpoint.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "driver-location"
                ],
                "summary": "Update driver location",
                "parameters": [
                    {
                        "description": "Driver location",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DriverLocationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AcceptedSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/driver/location/batch": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "driver-location"
                ],
                "summary": "Update driver locations in batch",
                "parameters": [
                    {
                        "description": "Driver location batch",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DriverLocationBatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AcceptedSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/driver/offline": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "driver"
                ],
                "summary": "Put driver offline",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DriverProfileSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/driver/online": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "driver"
                ],
                "summary": "Put driver online",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DriverProfileSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/driver/orders/current": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mobile reconnect sync endpoint. Response includes allowed_actions for driver UI.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "driver-orders"
                ],
                "summary": "Get current driver order",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DriverOrderSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/driver/orders/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "driver-orders"
                ],
                "summary": "Get driver order history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DriverOrderHistorySuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/driver/orders/{id}/accept": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "driver-orders"
                ],
                "summary": "Accept offered order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DriverOrderSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/driver/orders/{id}/arrived": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "driver-orders"
                ],
                "summary": "Mark driver arrived",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DriverOrderSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/driver/orders/{id}/complete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "driver-orders"
                ],
                "summary": "Complete driver trip",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Completion request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CompleteOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DriverOrderSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/driver/orders/{id}/reject": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "driver-orders"
                ],
                "summary": "Reject offered order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reject reason",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RejectOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AcceptedSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/driver/orders/{id}/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "driver-orders"
                ],
                "summary": "Start driver trip",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DriverOrderSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/driver/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "driver"
                ],
                "summary": "Get driver profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DriverProfileSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "driver"
                ],
                "summary": "Update driver profile",
                "parameters": [
                    {
                        "description": "Driver profile patch",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DriverProfilePatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DriverProfileSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns public API health status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "API health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_api.apiHealthResponse"
                        }
                    }
                }
            }
        },
        "/health/live": {
            "get": {
                "description": "Returns process liveness status for orchestrators.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_api.healthResponse"
                        }
                    }
                }
            }
        },
        "/health/ready": {
            "get": {
                "description": "Returns readiness status for traffic routing.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_api.healthResponse"
                        }
                    }
                }
            }
        },
        "/orders/current": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns current active trip state for reconnect recovery.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Get current order",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.CurrentOrderResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/passenger/orders": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passenger-orders"
                ],
                "summary": "Create passenger order",
                "parameters": [
                    {
                        "description": "Order request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PassengerCreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.PassengerOrderSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/passenger/orders/current": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mobile reconnect sync endpoint. Response includes allowed_actions for passenger UI.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passenger-orders"
                ],
                "summary": "Get current passenger order",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PassengerOrderSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/passenger/orders/estimate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns estimated distance, duration and tariff price for mobile order form.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passenger-orders"
                ],
                "summary": "Estimate passenger order",
                "parameters": [
                    {
                        "description": "Order estimate request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.OrderEstimateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.OrderEstimateSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/passenger/orders/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passenger-orders"
                ],
                "summary": "Get passenger order history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PassengerOrderHistorySuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/passenger/orders/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passenger-orders"
                ],
                "summary": "Get passenger order by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PassengerOrderSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/passenger/orders/{id}/cancel": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passenger-orders"
                ],
                "summary": "Cancel passenger order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cancellation reason",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CancelOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PassengerOrderSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/passenger/orders/{id}/rate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passenger-orders"
                ],
                "summary": "Rate completed passenger order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Order rating",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PassengerOrderSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/passenger/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passenger"
                ],
                "summary": "Get passenger profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PassengerProfileSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passenger"
                ],
                "summary": "Create passenger profile",
                "parameters": [
                    {
                        "description": "Passenger profile",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PassengerProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.PassengerProfileSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passenger"
                ],
                "summary": "Update passenger profile",
                "parameters": [
                    {
                        "description": "Passenger profile patch",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.PassengerProfilePatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PassengerProfileSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        },
        "/ws": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mobile realtime endpoint. JWT can be passed in Authorization header or token query parameter. After reconnect the server emits sync.required and the client must call the current order REST endpoint.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "websocket"
                ],
                "summary": "Connect mobile WebSocket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT token fallback for mobile clients",
                        "name": "token",
                        "in": "query"
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cmd_api.apiHealthResponse": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "example": "taxi-platform"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "cmd_api.healthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "dto.AssignedDriverDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "55555555-5555-5555-5555-555555555555"
                },
                "name": {
                    "type": "string",
                    "example": "Ivan"
                },
                "phone": {
                    "type": "string",
                    "example": "+79990000001"
                },
                "rating": {
                    "type": "number",
                    "example": 4.95
                }
            }
        },
        "dto.AuthCodeSentResponse": {
            "type": "object",
            "properties": {
                "delivery_channel": {
                    "type": "string",
                    "example": "sms"
                },
                "message": {
                    "type": "string",
                    "example": "verification code sent"
                }
            }
        },
        "dto.AuthLoginRequest": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "phone": {
                    "type": "string",
                    "example": "+79990000000"
                },
                "role": {
                    "enum": [
                        "passenger",
                        "driver",
                        "taxi_park",
                        "admin",
                        "dispatcher"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_internal_domain.UserRole"
                        }
                    ],
                    "example": "passenger"
                }
            }
        },
        "dto.AuthTokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOi..."
                },
                "expires_in": {
                    "type": "integer",
                    "example": 900
                },
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOi..."
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                }
            }
        },
        "dto.AuthVerifyCodeRequest": {
            "type": "object",
            "required": [
                "code",
                "role"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "123456"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "phone": {
                    "type": "string",
                    "example": "+79990000000"
                },
                "role": {
                    "enum": [
                        "passenger",
                        "driver",
                        "taxi_park",
                        "admin",
                        "dispatcher"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_internal_domain.UserRole"
                        }
                    ],
                    "example": "passenger"
                }
            }
        },
        "dto.CancelOrderRequest": {
            "type": "object",
            "required": [
                "reason"
            ],
            "properties": {
                "reason": {
                    "type": "string",
                    "example": "Passenger changed plans"
                }
            }
        },
        "dto.CarDTO": {
            "type": "object",
            "properties": {
                "brand": {
                    "type": "string",
                    "example": "Lada"
                },
                "color": {
                    "type": "string",
                    "example": "White"
                },
                "id": {
                    "type": "string",
                    "example": "77777777-7777-7777-7777-777777777777"
                },
                "model": {
                    "type": "string",
                    "example": "Vesta"
                },
                "plate_number": {
                    "type": "string",
                    "example": "A001AA196"
                }
            }
        },
        "dto.CompleteOrderRequest": {
            "type": "object",
            "required": [
                "currency",
                "final_price"
            ],
            "properties": {
                "currency": {
                    "type": "string",
                    "example": "RUB"
                },
                "final_price": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 260
                }
            }
        },
        "dto.CoordinatesRequest": {
            "type": "object",
            "required": [
                "latitude",
                "longitude"
            ],
            "properties": {
                "latitude": {
                    "type": "number",
                    "maximum": 90,
                    "minimum": -90,
                    "example": 56.838011
                },
                "longitude": {
                    "type": "number",
                    "maximum": 180,
                    "minimum": -180,
                    "example": 60.597465
                }
            }
        },
        "dto.CoordinatesResponse": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number",
                    "example": 56.838011
                },
                "longitude": {
                    "type": "number",
                    "example": 60.597465
                }
            }
        },
        "dto.CurrentOrderResponse": {
            "type": "object",
            "properties": {
                "order": {
                    "$ref": "#/definitions/dto.OrderResponse"
                }
            }
        },
        "dto.DriverLocationBatchRequest": {
            "type": "object",
            "required": [
                "locations"
            ],
            "properties": {
                "locations": {
                    "type": "array",
                    "maxItems": 50,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/dto.DriverLocationRequest"
                    }
                }
            }
        },
        "dto.DriverLocationRequest": {
            "type": "object",
            "required": [
                "location"
            ],
            "properties": {
                "accuracy_meters": {
                    "type": "number",
                    "minimum": 0,
                    "example": 12.5
                },
                "heading": {
                    "type": "integer",
                    "maximum": 359,
                    "minimum": 0,
                    "example": 90
                },
                "location": {
                    "$ref": "#/definitions/dto.CoordinatesRequest"
                },
                "speed_mps": {
                    "type": "number",
                    "minimum": 0,
                    "example": 8.3
                }
            }
        },
        "dto.DriverOrderHistoryResponse": {
            "type": "object",
            "properties": {
                "orders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.DriverOrderResponse"
                    }
                }
            }
        },
        "dto.DriverOrderResponse": {
            "type": "object",
            "properties": {
                "allowed_actions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "arrived",
                        "call_passenger"
                    ]
                },
                "comment": {
                    "type": "string",
                    "example": "Entrance 2"
                },
                "destination_point": {
                    "$ref": "#/definitions/dto.PointDTO"
                },
                "order_id": {
                    "type": "string",
                    "example": "44444444-4444-4444-4444-444444444444"
                },
                "passenger": {
                    "$ref": "#/definitions/dto.PassengerBriefDTO"
                },
                "pickup_point": {
                    "$ref": "#/definitions/dto.PointDTO"
                },
                "price": {
                    "$ref": "#/definitions/dto.MoneyResponse"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_internal_domain.OrderStatus"
                        }
                    ],
                    "example": "driver_assigned"
                },
                "timeline": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.OrderTimelineItem"
                    }
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "dto.DriverProfilePatchRequest": {
            "type": "object",
            "properties": {
                "license_number": {
                    "type": "string",
                    "example": "7700000000"
                },
                "name": {
                    "type": "string",
                    "example": "Ivan"
                }
            }
        },
        "dto.DriverProfileResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "22222222-2222-2222-2222-222222222222"
                },
                "is_verified": {
                    "type": "boolean",
                    "example": true
                },
                "license_number": {
                    "type": "string",
                    "example": "7700000000"
                },
                "name": {
                    "type": "string",
                    "example": "Ivan"
                },
                "phone": {
                    "type": "string",
                    "example": "+79990000001"
                },
                "rating": {
                    "type": "number",
                    "example": 4.95
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_internal_domain.DriverStatus"
                        }
                    ],
                    "example": "online"
                },
                "user_id": {
                    "type": "string",
                    "example": "33333333-3333-3333-3333-333333333333"
                }
            }
        },
        "dto.LogoutRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOi..."
                }
            }
        },
        "dto.MoneyResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer",
                    "example": 25000
                },
                "currency": {
                    "type": "string",
                    "example": "RUB"
                }
            }
        },
        "dto.OrderEstimateRequest": {
            "type": "object",
            "required": [
                "city_id",
                "destination_location",
                "pickup_location",
                "tariff_id"
            ],
            "properties": {
                "city_id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                },
                "destination_location": {
                    "$ref": "#/definitions/dto.CoordinatesRequest"
                },
                "pickup_location": {
                    "$ref": "#/definitions/dto.CoordinatesRequest"
                },
                "tariff_id": {
                    "type": "string",
                    "example": "22222222-2222-2222-2222-222222222222"
                }
            }
        },
        "dto.OrderEstimateResponse": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string",
                    "example": "RUB"
                },
                "distance_km": {
                    "type": "number",
                    "example": 4.2
                },
                "duration_min": {
                    "type": "integer",
                    "example": 11
                },
                "price": {
                    "type": "integer",
                    "example": 250
                },
                "price_type": {
                    "type": "string",
                    "example": "estimated"
                },
                "tariff_id": {
                    "type": "string",
                    "example": "22222222-2222-2222-2222-222222222222"
                },
                "tariff_name": {
                    "type": "string",
                    "example": "Economy"
                }
            }
        },
        "dto.OrderHistoryResponse": {
            "type": "object",
            "properties": {
                "orders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PassengerOrderResponse"
                    }
                }
            }
        },
        "dto.OrderResponse": {
            "type": "object",
            "properties": {
                "city_id": {
                    "type": "string"
                },
                "destination_address": {
                    "type": "string"
                },
                "driver_id": {
                    "type": "string"
                },
                "estimated_price": {
                    "$ref": "#/definitions/dto.MoneyResponse"
                },
                "final_price": {
                    "$ref": "#/definitions/dto.MoneyResponse"
                },
                "id": {
                    "type": "string"
                },
                "passenger_id": {
                    "type": "string"
                },
                "payment_method": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_internal_domain.PaymentMethod"
                        }
                    ],
                    "example": "cash"
                },
                "pickup_address": {
                    "type": "string"
                },
                "pickup_location": {
                    "$ref": "#/definitions/dto.CoordinatesResponse"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_internal_domain.OrderStatus"
                        }
                    ],
                    "example": "searching"
                },
                "tariff_id": {
                    "type": "string"
                },
                "version": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "dto.OrderTimelineItem": {
            "type": "object",
            "properties": {
                "occurred_at": {
                    "type": "string",
                    "example": "2026-05-12T12:00:00Z"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_internal_domain.OrderStatus"
                        }
                    ],
                    "example": "driver_assigned"
                }
            }
        },
        "dto.PassengerBriefDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "66666666-6666-6666-6666-666666666666"
                },
                "name": {
                    "type": "string",
                    "example": "Irina"
                },
                "phone": {
                    "type": "string",
                    "example": "+79990000000"
                }
            }
        },
        "dto.PassengerCreateOrderRequest": {
            "type": "object",
            "required": [
                "city_id",
                "destination_address",
                "destination_location",
                "payment_type",
                "pickup_address",
                "pickup_location",
                "tariff_id"
            ],
            "properties": {
                "city_id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                },
                "comment": {
                    "type": "string",
                    "example": "Entrance 2"
                },
                "destination_address": {
                    "type": "string",
                    "example": "Mira 10"
                },
                "destination_location": {
                    "$ref": "#/definitions/dto.CoordinatesRequest"
                },
                "passenger_phone": {
                    "type": "string",
                    "example": "+79990000000"
                },
                "payment_type": {
                    "enum": [
                        "cash",
                        "card",
                        "corporate"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_internal_domain.PaymentMethod"
                        }
                    ],
                    "example": "cash"
                },
                "pickup_address": {
                    "type": "string",
                    "example": "Lenina 1"
                },
                "pickup_location": {
                    "$ref": "#/definitions/dto.CoordinatesRequest"
                },
                "tariff_id": {
                    "type": "string",
                    "example": "22222222-2222-2222-2222-222222222222"
                }
            }
        },
        "dto.PassengerOrderResponse": {
            "type": "object",
            "properties": {
                "allowed_actions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "cancel",
                        "call_driver"
                    ]
                },
                "car": {
                    "$ref": "#/definitions/dto.CarDTO"
                },
                "destination_point": {
                    "$ref": "#/definitions/dto.PointDTO"
                },
                "driver": {
                    "$ref": "#/definitions/dto.AssignedDriverDTO"
                },
                "eta_seconds": {
                    "type": "integer",
                    "example": 420
                },
                "order_id": {
                    "type": "string",
                    "example": "44444444-4444-4444-4444-444444444444"
                },
                "pickup_point": {
                    "$ref": "#/definitions/dto.PointDTO"
                },
                "price": {
                    "$ref": "#/definitions/dto.MoneyResponse"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_internal_domain.OrderStatus"
                        }
                    ],
                    "example": "driver_arriving"
                },
                "timeline": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.OrderTimelineItem"
                    }
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "dto.PassengerProfilePatchRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "irina@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "Irina"
                }
            }
        },
        "dto.PassengerProfileRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "irina@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "Irina"
                }
            }
        },
        "dto.PassengerProfileResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "irina@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                },
                "name": {
                    "type": "string",
                    "example": "Irina"
                },
                "phone": {
                    "type": "string",
                    "example": "+79990000000"
                }
            }
        },
        "dto.PointDTO": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Lenina 1"
                },
                "location": {
                    "$ref": "#/definitions/dto.CoordinatesResponse"
                }
            }
        },
        "dto.RateOrderRequest": {
            "type": "object",
            "required": [
                "score"
            ],
            "properties": {
                "comment": {
                    "type": "string",
                    "example": "Good driver"
                },
                "score": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 5
                }
            }
        },
        "dto.RefreshTokenRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOi..."
                }
            }
        },
        "dto.RejectOrderRequest": {
            "type": "object",
            "required": [
                "reason"
            ],
            "properties": {
                "reason": {
                    "type": "string",
                    "example": "Too far"
                }
            }
        },
        "dto.StartRegistrationRequest": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "password",
                "personal_data_consent",
                "phone",
                "privacy_policy_version",
                "registration_type",
                "terms_accepted",
                "terms_version"
            ],
            "properties": {
                "city_id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "Ivan"
                },
                "last_name": {
                    "type": "string",
                    "example": "Petrov"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "strong-password"
                },
                "personal_data_consent": {
                    "type": "boolean",
                    "example": true
                },
                "phone": {
                    "type": "string",
                    "example": "+79990000000"
                },
                "privacy_policy_version": {
                    "type": "string",
                    "example": "1.0"
                },
                "registration_type": {
                    "enum": [
                        "passenger",
                        "driver",
                        "taxi_park"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_internal_domain.RegistrationType"
                        }
                    ],
                    "example": "passenger"
                },
                "taxi_park": {
                    "$ref": "#/definitions/dto.TaxiParkRegistration"
                },
                "terms_accepted": {
                    "type": "boolean",
                    "example": true
                },
                "terms_version": {
                    "type": "string",
                    "example": "1.0"
                }
            }
        },
        "dto.TaxiParkRegistration": {
            "type": "object",
            "properties": {
                "legal_name": {
                    "type": "string",
                    "example": "North Taxi Park LLC"
                },
                "name": {
                    "type": "string",
                    "example": "North Taxi Park"
                },
                "tax_id": {
                    "type": "string",
                    "example": "7700000000"
                }
            }
        },
        "github_com_kishert-lab_taxi-platform_internal_domain.DriverStatus": {
            "type": "string",
            "enum": [
                "offline",
                "online",
                "busy",
                "paused",
                "blocked"
            ],
            "x-enum-varnames": [
                "DriverStatusOffline",
                "DriverStatusOnline",
                "DriverStatusBusy",
                "DriverStatusPaused",
                "DriverStatusBlocked"
            ]
        },
        "github_com_kishert-lab_taxi-platform_internal_domain.OrderStatus": {
            "type": "string",
            "enum": [
                "created",
                "searching",
                "driver_assigned",
                "driver_arriving",
                "driver_waiting",
                "in_progress",
                "completed",
                "cancelled",
                "failed"
            ],
            "x-enum-varnames": [
                "OrderStatusCreated",
                "OrderStatusSearching",
                "OrderStatusDriverAssigned",
                "OrderStatusDriverArriving",
                "OrderStatusDriverWaiting",
                "OrderStatusInProgress",
                "OrderStatusCompleted",
                "OrderStatusCancelled",
                "OrderStatusFailed"
            ]
        },
        "github_com_kishert-lab_taxi-platform_internal_domain.PaymentMethod": {
            "type": "string",
            "enum": [
                "cash",
                "card",
                "corporate"
            ],
            "x-enum-varnames": [
                "PaymentMethodCash",
                "PaymentMethodCard",
                "PaymentMethodCorporate"
            ]
        },
        "github_com_kishert-lab_taxi-platform_internal_domain.RegistrationType": {
            "type": "string",
            "enum": [
                "passenger",
                "driver",
                "taxi_park"
            ],
            "x-enum-varnames": [
                "RegistrationTypePassenger",
                "RegistrationTypeDriver",
                "RegistrationTypeTaxiPark"
            ]
        },
        "github_com_kishert-lab_taxi-platform_internal_domain.UserRole": {
            "type": "string",
            "enum": [
                "passenger",
                "driver",
                "taxi_park",
                "admin",
                "dispatcher"
            ],
            "x-enum-varnames": [
                "UserRolePassenger",
                "UserRoleDriver",
                "UserRoleTaxiPark",
                "UserRoleAdmin",
                "UserRoleDispatcher"
            ]
        },
        "github_com_kishert-lab_taxi-platform_pkg_response.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.ErrorBody"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Meta"
                }
            }
        },
        "github_com_kishert-lab_taxi-platform_pkg_response.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.ErrorCode"
                        }
                    ],
                    "example": "ORDER_NOT_FOUND"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string",
                    "example": "Order not found"
                }
            }
        },
        "github_com_kishert-lab_taxi-platform_pkg_response.ErrorCode": {
            "type": "string",
            "enum": [
                "VALIDATION_ERROR",
                "UNAUTHORIZED",
                "FORBIDDEN",
                "ORDER_NOT_FOUND",
                "ORDER_INVALID_STATE",
                "DRIVER_NOT_AVAILABLE",
                "ORDER_ALREADY_ASSIGNED",
                "DISPATCH_IN_PROGRESS",
                "RATE_LIMITED",
                "CONSENT_REQUIRED",
                "INTERNAL_ERROR"
            ],
            "x-enum-varnames": [
                "CodeValidationError",
                "CodeUnauthorized",
                "CodeForbidden",
                "CodeOrderNotFound",
                "CodeOrderInvalidState",
                "CodeDriverNotAvailable",
                "CodeOrderAlreadyAssigned",
                "CodeDispatchInProgress",
                "CodeRateLimited",
                "CodeConsentRequired",
                "CodeInternalError"
            ]
        },
        "github_com_kishert-lab_taxi-platform_pkg_response.Meta": {
            "type": "object",
            "properties": {
                "request_id": {
                    "type": "string",
                    "example": "11111111-1111-1111-1111-111111111111"
                }
            }
        },
        "github_com_kishert-lab_taxi-platform_pkg_response.Success": {
            "type": "object",
            "properties": {
                "data": {},
                "meta": {
                    "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Meta"
                }
            }
        },
        "handler.AcceptedSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handler.acceptedResponse"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Meta"
                }
            }
        },
        "handler.AuthCodeSentSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.AuthCodeSentResponse"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Meta"
                }
            }
        },
        "handler.AuthTokenSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.AuthTokenResponse"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Meta"
                }
            }
        },
        "handler.DriverOrderHistorySuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.DriverOrderHistoryResponse"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Meta"
                }
            }
        },
        "handler.DriverOrderSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.DriverOrderResponse"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Meta"
                }
            }
        },
        "handler.DriverProfileSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.DriverProfileResponse"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Meta"
                }
            }
        },
        "handler.OrderEstimateSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.OrderEstimateResponse"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Meta"
                }
            }
        },
        "handler.PassengerOrderHistorySuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.OrderHistoryResponse"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Meta"
                }
            }
        },
        "handler.PassengerOrderSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.PassengerOrderResponse"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Meta"
                }
            }
        },
        "handler.PassengerProfileSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.PassengerProfileResponse"
                },
                "meta": {
                    "$ref": "#/definitions/github_com_kishert-lab_taxi-platform_pkg_response.Meta"
                }
            }
        },
        "handler.acceptedResponse": {
            "type": "object",
            "properties": {
                "accepted": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "handler.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "personal data consent required"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter the token with the ` + "`" + `Bearer ` + "`" + ` prefix, for example: Bearer eyJhbGciOi...",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Taxi Platform API",
	Description:      "Production-grade taxi backend API for small cities and rural areas.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
